# Generated by Django 3.1.6 on 2021-02-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_categorys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categorys',
            field=models.CharField(choices=[('HTML', 'HTML(CSS)'), ('DATA', 'Data(DB)'), ('ALGO', 'Algorithm'), ('CLNG', 'C'), ('JVSC', 'Javascript'), ('JAVA', 'Java'), ('CPSC', 'ComScience'), ('PYTH', 'Python'), ('PROJ', 'Project')], max_length=80, null=True),
        ),
    ]
